version: 2
jobs: 
  build:
    docker:
        - image: circleci/golang:1.14  
    steps:
        - checkout
        - run: ls
        - run: go test github.com/hunkeelin/oktalib
        - run: go test github.com/hunkeelin/userprompt
        - run: go test -v 
