version: 2
  jobs: 
    build:
      steps:
        - checkout
        - run: ls
        - run: go run  -v ./...
      requires:
        - build
            filters:
              branches:
                only:master
