version: 2
  jobs: 
    build:
      docker:
        - image: circleci/golang:1.14  
      steps:
        - checkout
        - run: ls
        - run: go run oktaPushVerify.go
workflows:
  version: 2
  build-workflow:
    jobs:
     - build 
       
