apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

        - name: backend-container
          image: redis
  replicas: 2 
  selector:
    matchLabels:
        type: front-end 
